version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest          # OSS or Enterprise, your choice
    container_name: grafana
    environment:
      # disable https only for development
      GF_SERVER_PROTOCOL: "http"            # use http instead of https
      GF_SERVER_HTTP_PORT: "3000"           # port to listen on
      # ----  security  ----
      GF_SECURITY_ADMIN_USER: stefan       # login name you want
      # read password from env variable
      # set this in your .env file or export it in your shell
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"      # disable self-register  :contentReference[oaicite:2]{index=2}
      GF_AUTH_ANONYMOUS_ENABLED: "false"   # disable anonymous auth  :contentReference[oaicite:3]{index=3}
      # ----  plugins  ----
      # Comma separated list; Infinity + CSV in this example
      GF_INSTALL_PLUGINS: "yesoreyeram-infinity-datasource,marcusolsson-csv-datasource"
                                            # installed automatically at boot :contentReference[oaicite:4]{index=4}
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - reporter

  reporter:
    build:
      context: ../
      dockerfile: grafana/Dockerfile
    volumes:
      - ~/.config/rclone:/home/appuser/.config/rclone
      - ~/.config/gtd.json:/home/appuser/.config/gtd.json
    environment:
      GRAFANA_URL: "http://grafana:3000"  # URL of the Grafana instance