name: Test Installation and Execution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9" 

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install build tools
      run: pip install build

    - name: Install the package
      run: |
        pip install .

    - name: Check if `gtd` command works
      run: |
        gtd --help
